"""initialize model

Revision ID: 515adb205290
Revises: 
Create Date: 2023-11-15 15:19:28.558520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515adb205290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
